using ClosedXML.Excel;
using Query2Excel.Core.Abstractions;
using Query2Excel.Core.Configuration;
using Query2Excel.Core.Models;
using Query2Excel.Core.Services;
using System.Diagnostics;
using System.Globalization;
using System.Text.Json;
using System.Text.Json.Nodes;

var builder = WebApplication.CreateBuilder(args);

builder.Configuration.AddJsonFile(
	Path.Combine(AppContext.BaseDirectory, "Query2Excel.RowStyles.json"),
	optional: true,
	reloadOnChange: false);

builder.Services.Configure<Query2ExcelOptions>(builder.Configuration.GetSection(Query2ExcelOptions.SectionName));
builder.Services.AddSingleton<IDatabaseExecutor, DatabaseExecutor>();
builder.Services.AddSingleton<IWorkbookBuilder, WorkbookBuilder>();
builder.Services.AddSingleton<IQuery2ExcelService, Query2ExcelService>();

var app = builder.Build();

app.UseDefaultFiles();
app.UseStaticFiles();

var launchBrowserOnStartup = builder.Configuration.GetValue<bool?>("Query2ExcelWeb:LaunchBrowserOnStartup") ?? true;
if (app.Environment.IsDevelopment() && launchBrowserOnStartup)
{
	app.Lifetime.ApplicationStarted.Register(() =>
	{
		var preferredHttpsUrl = app.Urls.FirstOrDefault(url => url.StartsWith("https://", StringComparison.OrdinalIgnoreCase));
		var fallbackHttpUrl = app.Urls.FirstOrDefault(url => url.StartsWith("http://", StringComparison.OrdinalIgnoreCase));
		var launchUrl = preferredHttpsUrl ?? fallbackHttpUrl;

		if (string.IsNullOrWhiteSpace(launchUrl))
		{
			return;
		}

		try
		{
			Process.Start(new ProcessStartInfo
			{
				FileName = launchUrl,
				UseShellExecute = true
			});
		}
		catch
		{
			// Browser launch is best-effort only.
		}
	});
}

app.MapGet("/settings", (IConfiguration configuration) =>
{
	var configuredRowStyleNames = configuration
		.GetSection($"{Query2ExcelOptions.SectionName}:RowStyles")
		.GetChildren()
		.Select(section => section.Key)
		.Where(name => !string.IsNullOrWhiteSpace(name))
		.ToArray();

	var response = new WebSettingsResponse
	{
		ConnectionStringTemplate = FirstNonEmpty(
			configuration["Query2ExcelWeb:ConnectionStringTemplate"],
			configuration["Query2Excel:ConnectionStringTemplate"],
			"Server=localhost;Database=CDMSandbox;User Id={UserId};Password={Password};TrustServerCertificate=True;"),
		UserId = FirstNonEmpty(
			configuration["Query2ExcelWeb:DatabaseUserId"],
			configuration["Query2Excel:DatabaseUserId"]),
		HasPassword = !string.IsNullOrWhiteSpace(FirstNonEmpty(
			configuration["Query2ExcelWeb:DatabasePassword"],
			configuration["Query2Excel:DatabasePassword"])),
		OpenWorkbookAfterGenerate = configuration.GetValue<bool?>("Query2ExcelWeb:OpenWorkbookAfterGenerate") ?? false,
		CommandTimeoutSeconds = 120,
		RowStyleNames = configuredRowStyleNames
	};

	return Results.Json(response);
});

app.MapPost("/workbook/load", async (HttpRequest request, CancellationToken cancellationToken) =>
{
	var form = await request.ReadFormAsync(cancellationToken).ConfigureAwait(false);
	var workbookFile = form.Files.GetFile("workbook");
	if (workbookFile is null || workbookFile.Length <= 0)
	{
		return Results.BadRequest("Workbook file is required.");
	}

	if (!string.Equals(Path.GetExtension(workbookFile.FileName), ".xlsx", StringComparison.OrdinalIgnoreCase))
	{
		return Results.BadRequest("Only .xlsx workbooks are supported.");
	}

	try
	{
		await using var workbookStream = workbookFile.OpenReadStream();
		using var workbook = new XLWorkbook(workbookStream);

		if (!TryReadRefreshDataFromSqlWorksheet(workbook, out var importData, out var validationError))
		{
			return Results.BadRequest(validationError);
		}

		return Results.Json(new WorkbookImportResponse
		{
			ConnectionStringTemplate = importData.ConnectionStringTemplate,
			SqlScript = importData.SqlScript,
			OutputFileName = SanitizeOutputFileName(workbookFile.FileName)
		});
	}
	catch (Exception)
	{
		return Results.BadRequest("Unable to read workbook. Ensure it is a valid .xlsx file generated by Query2Excel.");
	}
});

app.MapPost("/run", async (RunWorkbookRequest request, IConfiguration configuration, IQuery2ExcelService service, CancellationToken cancellationToken) =>
{
	var providedTemplate = request.ConnectionStringTemplate?.Trim();
	var providedUserId = request.UserId?.Trim();
	var providedPassword = request.Password;

	if (!string.IsNullOrWhiteSpace(providedTemplate)
		|| !string.IsNullOrWhiteSpace(providedUserId)
		|| !string.IsNullOrWhiteSpace(providedPassword))
	{
		PersistWebSecrets(providedTemplate, providedUserId, providedPassword);
	}

	var requestedTemplate = FirstNonEmpty(
		providedTemplate,
		configuration["Query2ExcelWeb:ConnectionStringTemplate"],
		configuration["Query2Excel:ConnectionStringTemplate"]);

	if (string.IsNullOrWhiteSpace(requestedTemplate))
	{
		return Results.BadRequest("Connection string template is required. Provide it in the form or set Query2ExcelWeb:ConnectionStringTemplate.");
	}

	if (string.IsNullOrWhiteSpace(request.SqlScript))
	{
		return Results.BadRequest("SQL script is required.");
	}

	if (!ValidateWebOutputFilePath(request.OutputFileName, out var outputPathValidationError))
	{
		return Results.BadRequest(outputPathValidationError);
	}

	string resolvedConnectionString;
	try
	{
		resolvedConnectionString = BuildConnectionString(requestedTemplate!, configuration, providedUserId, providedPassword);
	}
	catch (ArgumentException exception)
	{
		return Results.BadRequest(exception.Message);
	}

	var baseTempDirectory = Path.Combine(Path.GetTempPath(), "Query2Excel", Guid.NewGuid().ToString("N"));
	Directory.CreateDirectory(baseTempDirectory);

	var scriptPath = Path.Combine(baseTempDirectory, "query.sql");
	var outputPath = Path.Combine(baseTempDirectory, "query2excel-output.xlsx");

	try
	{
		await File.WriteAllTextAsync(scriptPath, request.SqlScript, cancellationToken).ConfigureAwait(false);

		var timeout = request.CommandTimeoutSeconds is > 0 ? request.CommandTimeoutSeconds.Value : 120;
		var executionRequest = new Query2ExcelRequest(
			resolvedConnectionString,
			scriptPath,
			outputPath,
			timeout,
			requestedTemplate);

		await service.RunAsync(executionRequest, cancellationToken).ConfigureAwait(false);

		var workbookBytes = await File.ReadAllBytesAsync(outputPath, cancellationToken).ConfigureAwait(false);
		var fileName = string.IsNullOrWhiteSpace(request.OutputFileName)
			? $"query2excel-{DateTime.UtcNow:yyyyMMdd-HHmmss}.xlsx"
			: SanitizeOutputFileName(request.OutputFileName!);

		if (TryResolveExplicitOutputPath(request.OutputFileName, out var resolvedOutputPath, out var resolvedOutputFileName))
		{
			var resolvedDirectory = Path.GetDirectoryName(resolvedOutputPath);
			if (!string.IsNullOrWhiteSpace(resolvedDirectory))
			{
				Directory.CreateDirectory(resolvedDirectory);
			}

			var backupFilePath = TryCreateVersionedBackup(resolvedOutputPath);

			await File.WriteAllBytesAsync(resolvedOutputPath, workbookBytes, cancellationToken).ConfigureAwait(false);

			if (request.OpenWithDefaultApp)
			{
				TryOpenPathWithDefaultApp(resolvedOutputPath);
			}

			return Results.Json(new RunWorkbookResponse
			{
				SavedToPath = resolvedOutputPath,
				FileName = resolvedOutputFileName,
				BackupFilePath = backupFilePath,
				Downloaded = false
			});
		}

		if (request.OpenWithDefaultApp)
		{
			TryOpenWorkbookWithDefaultApp(workbookBytes, fileName);
		}

		return Results.File(
			workbookBytes,
			"application/vnd.openxmlformats-officedocument.spreadsheetml.sheet",
			fileName);
	}
	finally
	{
		if (Directory.Exists(baseTempDirectory))
		{
			Directory.Delete(baseTempDirectory, recursive: true);
		}
	}
});

app.Run();

static string BuildConnectionString(string connectionStringTemplate, IConfiguration configuration, string? providedUserId, string? providedPassword)
{
	var template = connectionStringTemplate.Trim();
	if (string.IsNullOrWhiteSpace(template))
	{
		throw new ArgumentException("Connection string template is required.");
	}

	var userIdTokens = new[] { "{UserId}", "{{USER_ID}}" };
	var passwordTokens = new[] { "{Password}", "{{PASSWORD}}" };

	var containsUserIdToken = userIdTokens.Any(token => template.Contains(token, StringComparison.OrdinalIgnoreCase));
	var containsPasswordToken = passwordTokens.Any(token => template.Contains(token, StringComparison.OrdinalIgnoreCase));

	if (!containsUserIdToken && !containsPasswordToken)
	{
		return template;
	}

	var userId = FirstNonEmpty(
		providedUserId,
		configuration["Query2ExcelWeb:DatabaseUserId"],
		configuration["Query2Excel:DatabaseUserId"]);

	var password = FirstNonEmpty(
		providedPassword,
		configuration["Query2ExcelWeb:DatabasePassword"],
		configuration["Query2Excel:DatabasePassword"]);

	if (containsUserIdToken && string.IsNullOrWhiteSpace(userId))
	{
		throw new ArgumentException("Database user id token was provided, but no User Secrets value was found for Query2ExcelWeb:DatabaseUserId.");
	}

	if (containsPasswordToken && string.IsNullOrWhiteSpace(password))
	{
		throw new ArgumentException("Database password token was provided, but no User Secrets value was found for Query2ExcelWeb:DatabasePassword.");
	}

	if (!string.IsNullOrWhiteSpace(userId))
	{
		foreach (var token in userIdTokens)
		{
			template = template.Replace(token, userId, StringComparison.OrdinalIgnoreCase);
		}
	}

	if (!string.IsNullOrWhiteSpace(password))
	{
		foreach (var token in passwordTokens)
		{
			template = template.Replace(token, password, StringComparison.OrdinalIgnoreCase);
		}
	}

	return template;
}

static void PersistWebSecrets(string? connectionStringTemplate, string? userId, string? password)
{
	var secretsPath = GetWebSecretsFilePath();
	var directoryPath = Path.GetDirectoryName(secretsPath);
	if (string.IsNullOrWhiteSpace(directoryPath))
	{
		return;
	}

	Directory.CreateDirectory(directoryPath);

	var root = File.Exists(secretsPath)
		? JsonNode.Parse(File.ReadAllText(secretsPath)) as JsonObject ?? new JsonObject()
		: new JsonObject();

	if (!string.IsNullOrWhiteSpace(connectionStringTemplate))
	{
		root["Query2ExcelWeb:ConnectionStringTemplate"] = connectionStringTemplate;
	}

	if (!string.IsNullOrWhiteSpace(userId))
	{
		root["Query2ExcelWeb:DatabaseUserId"] = userId;
	}

	if (!string.IsNullOrWhiteSpace(password))
	{
		root["Query2ExcelWeb:DatabasePassword"] = password;
	}

	var options = new JsonSerializerOptions { WriteIndented = true };
	File.WriteAllText(secretsPath, root.ToJsonString(options));
}

static string GetWebSecretsFilePath()
{
	const string webUserSecretsId = "query2excel-web-e08a2d8c-3b2a-4d08-b23b-43b7f35c4a4f";

	if (OperatingSystem.IsWindows())
	{
		var appData = Environment.GetFolderPath(Environment.SpecialFolder.ApplicationData);
		return Path.Combine(appData, "Microsoft", "UserSecrets", webUserSecretsId, "secrets.json");
	}

	var home = Environment.GetFolderPath(Environment.SpecialFolder.UserProfile);
	return Path.Combine(home, ".microsoft", "usersecrets", webUserSecretsId, "secrets.json");
}

static string? FirstNonEmpty(params string?[] values)
{
	return values.FirstOrDefault(value => !string.IsNullOrWhiteSpace(value));
}

static string SanitizeOutputFileName(string rawName)
{
	var normalized = rawName.Trim().Trim('"', '\'');
	normalized = normalized.Replace('\\', '/');
	normalized = Path.GetFileName(normalized);

	if (string.IsNullOrWhiteSpace(normalized))
	{
		return "query2excel-output.xlsx";
	}

	if (!normalized.EndsWith(".xlsx", StringComparison.OrdinalIgnoreCase))
	{
		normalized += ".xlsx";
	}

	foreach (var invalidChar in Path.GetInvalidFileNameChars())
	{
		normalized = normalized.Replace(invalidChar, '_');
	}

	return normalized;
}

static bool TryResolveExplicitOutputPath(string? rawOutputPathOrFileName, out string resolvedOutputPath, out string resolvedOutputFileName)
{
	resolvedOutputPath = string.Empty;
	resolvedOutputFileName = string.Empty;

	if (string.IsNullOrWhiteSpace(rawOutputPathOrFileName))
	{
		return false;
	}

	var rawValue = rawOutputPathOrFileName.Trim().Trim('"', '\'');
	if (string.IsNullOrWhiteSpace(rawValue))
	{
		return false;
	}

	var hasPathComponent =
		Path.IsPathRooted(rawValue)
		|| rawValue.Contains(Path.DirectorySeparatorChar)
		|| rawValue.Contains(Path.AltDirectorySeparatorChar);

	if (!hasPathComponent)
	{
		return false;
	}

	var candidatePath = rawValue;
	if (!Path.HasExtension(candidatePath))
	{
		candidatePath += ".xlsx";
	}

	var fullPath = Path.IsPathRooted(candidatePath)
		? Path.GetFullPath(candidatePath)
		: Path.GetFullPath(Path.Combine(Directory.GetCurrentDirectory(), candidatePath));

	var directory = Path.GetDirectoryName(fullPath);
	if (string.IsNullOrWhiteSpace(directory))
	{
		return false;
	}

	var safeFileName = SanitizeOutputFileName(Path.GetFileName(fullPath));
	resolvedOutputPath = Path.Combine(directory, safeFileName);
	resolvedOutputFileName = safeFileName;
	return true;
}

static bool ValidateWebOutputFilePath(string? rawOutputPathOrFileName, out string? validationError)
{
	validationError = null;

	if (string.IsNullOrWhiteSpace(rawOutputPathOrFileName))
	{
		return true;
	}

	var trimmed = rawOutputPathOrFileName.Trim().Trim('"', '\'');
	if (string.IsNullOrWhiteSpace(trimmed))
	{
		return true;
	}

	if (trimmed.EndsWith("\\", StringComparison.Ordinal) || trimmed.EndsWith("/", StringComparison.Ordinal))
	{
		validationError = "Output file path must include a file name ending with .xlsx.";
		return false;
	}

	var extension = Path.GetExtension(trimmed);
	if (!string.IsNullOrWhiteSpace(extension)
		&& !string.Equals(extension, ".xlsx", StringComparison.OrdinalIgnoreCase))
	{
		validationError = "Output file path must point to a .xlsx file.";
		return false;
	}

	return true;
}

static string? TryCreateVersionedBackup(string filePath)
{
	if (!File.Exists(filePath))
	{
		return null;
	}

	var backupPath = GetNextVersionedBackupPath(filePath);
	File.Move(filePath, backupPath);
	return backupPath;
}

static string GetNextVersionedBackupPath(string filePath)
{
	for (var version = 1; version < int.MaxValue; version++)
	{
		var candidate = filePath + version.ToString(CultureInfo.InvariantCulture);
		if (!File.Exists(candidate))
		{
			return candidate;
		}
	}

	throw new InvalidOperationException($"Unable to create a versioned backup for '{filePath}'.");
}

static bool TryReadRefreshDataFromSqlWorksheet(XLWorkbook workbook, out WorkbookRefreshData importData, out string? validationError)
{
	importData = new WorkbookRefreshData(string.Empty, string.Empty);
	validationError = null;

	if (!workbook.Worksheets.TryGetWorksheet("SQL", out var sqlWorksheet))
	{
		validationError = "Workbook validation failed: SQL worksheet was not found.";
		return false;
	}

	if (!string.Equals(sqlWorksheet.Cell("A1").GetString().Trim(), "Query2Excel Execution Details", StringComparison.OrdinalIgnoreCase))
	{
		validationError = "Workbook validation failed: SQL worksheet header is not in the expected format.";
		return false;
	}

	if (!string.Equals(sqlWorksheet.Cell("A7").GetString().Trim(), "Connection String Template", StringComparison.OrdinalIgnoreCase))
	{
		validationError = "Workbook validation failed: Connection String Template field is missing from SQL worksheet.";
		return false;
	}

	if (!string.Equals(sqlWorksheet.Cell("A9").GetString().Trim(), "Executed SQL", StringComparison.OrdinalIgnoreCase))
	{
		validationError = "Workbook validation failed: Executed SQL field is missing from SQL worksheet.";
		return false;
	}

	var connectionStringTemplate = sqlWorksheet.Cell("B7").GetString().Trim();
	if (string.IsNullOrWhiteSpace(connectionStringTemplate))
	{
		validationError = "Workbook validation failed: Connection String Template value is empty.";
		return false;
	}

	var sqlScript = sqlWorksheet.Cell("A10").GetString();
	if (string.IsNullOrWhiteSpace(sqlScript))
	{
		validationError = "Workbook validation failed: Executed SQL value is empty.";
		return false;
	}

	importData = new WorkbookRefreshData(connectionStringTemplate, sqlScript);
	return true;
}

static void TryOpenPathWithDefaultApp(string path)
{
	try
	{
		Process.Start(new ProcessStartInfo
		{
			FileName = path,
			UseShellExecute = true
		});
	}
	catch
	{
		// Opening with default app is best-effort only.
	}
}

static void TryOpenWorkbookWithDefaultApp(byte[] workbookBytes, string outputFileName)
{
	if (workbookBytes.Length == 0)
	{
		return;
	}

	try
	{
		var openDirectory = Path.Combine(Path.GetTempPath(), "Query2Excel", "OpenedWorkbooks");
		Directory.CreateDirectory(openDirectory);

		var fileName = SanitizeOutputFileName(outputFileName);
		var uniqueFileName = $"{DateTime.UtcNow:yyyyMMdd-HHmmss}-{Guid.NewGuid():N}-{fileName}";
		var openPath = Path.Combine(openDirectory, uniqueFileName);

		File.WriteAllBytes(openPath, workbookBytes);
		TryOpenPathWithDefaultApp(openPath);
	}
	catch
	{
		// Opening with default app is best-effort only.
	}
}

internal sealed class RunWorkbookRequest
{
	public string? ConnectionStringTemplate { get; init; }

	public string? UserId { get; init; }

	public string? Password { get; init; }

	public string? SqlScript { get; init; }

	public int? CommandTimeoutSeconds { get; init; }

	public string? OutputFileName { get; init; }

	public bool OpenWithDefaultApp { get; init; }
}

internal sealed class WebSettingsResponse
{
	public string? ConnectionStringTemplate { get; init; }

	public string? UserId { get; init; }

	public bool HasPassword { get; init; }

	public bool OpenWorkbookAfterGenerate { get; init; }

	public int CommandTimeoutSeconds { get; init; }

	public string[] RowStyleNames { get; init; } = Array.Empty<string>();
}

internal sealed class RunWorkbookResponse
{
	public string? SavedToPath { get; init; }

	public string? FileName { get; init; }

	public string? BackupFilePath { get; init; }

	public bool Downloaded { get; init; }
}

internal sealed class WorkbookImportResponse
{
	public string? ConnectionStringTemplate { get; init; }

	public string? SqlScript { get; init; }

	public string? OutputFileName { get; init; }
}

internal readonly record struct WorkbookRefreshData(string ConnectionStringTemplate, string SqlScript);

public partial class Program;
