<Project Sdk="Microsoft.NET.Sdk.Web">

  <ItemGroup>
    <ProjectReference Include="..\Query2Excel.Core\Query2Excel.Core.csproj" />
    <Content Include="..\config\Query2Excel.RowStyles.json">
      <Link>Query2Excel.RowStyles.json</Link>
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
      <CopyToPublishDirectory>PreserveNewest</CopyToPublishDirectory>
    </Content>
  </ItemGroup>

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UserSecretsId>query2excel-web-e08a2d8c-3b2a-4d08-b23b-43b7f35c4a4f</UserSecretsId>
  </PropertyGroup>

</Project>
